language: python
dist: xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.7
      env: OLD_SPHINX=1.7
    - python: 3.7
      env: OLD_SPHINX=1.8
    - python: 3.7
      env: OLD_SPHINX=2.0
    - python: 3.7
      env: OLD_SPHINX=2.4

script:
  - ci/travis.sh
